  clientservice:
    build: .
    container_name: clientservice
    ports:
      - 5019:80
      - 7149:443
    environment:
        ASPNETCORE_URLS: "https://+;http://+"
        ASPNETCORE_HTTPS_PORT: "7149"
        ASPNETCORE_ENVIRONMENT: "Development"
        Host: "host.docker.internal"
        Port: "1401"
        Database: "ClientsDB"
        UserId: "sa"
        Password: "Sql1234!"
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/