version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    command:
      - /bin/bash
      - ./entrypoint.sh
    ports:
      - 1401:1433
    volumes:
      - ./data:/var/lib/mssqlql/data
      - ./db/mssql/docker-entrypoint.sh:/entrypoint.sh
      - ./db/mssql/docker-db-init.sh:/db-init.sh
      - ./db/mssql/mssql-dbs.sql:/db-init.sql
    environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "Sql1234!"
  clientservice:
    image: clientservice:dev
    build: ../clientservice
    container_name: clientservice
    ports:
      - 5019:80
      - 7149:443
    environment:
        ASPNETCORE_URLS: "https://+;http://+"
        ASPNETCORE_HTTPS_PORT: "7149"
        ASPNETCORE_ENVIRONMENT: "Development"
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/
  accountservice:
    image: accountservice:dev
    build: ../accountservice
    container_name: accountservice
    ports:
      - 5028:80
      - 7002:443
    environment:
        ASPNETCORE_URLS: "https://+;http://+"
        ASPNETCORE_HTTPS_PORT: "7002"
        ASPNETCORE_ENVIRONMENT: "Development"
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/
  transactionservice:
    image: transactionservice:dev
    build: ../transactionservice
    container_name: transactionservice
    ports:
      - 5068:80
      - 7009:443
    environment:
        ASPNETCORE_URLS: "https://+;http://+"
        ASPNETCORE_HTTPS_PORT: "7009"
        ASPNETCORE_ENVIRONMENT: "Development"
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/