  accountservice:
    build: .
    container_name: accountservice
    ports:
      - 5028:80
      - 7002:443
    environment:
        ASPNETCORE_URLS: "https://+;http://+"
        ASPNETCORE_HTTPS_PORT: "7002"
        ASPNETCORE_ENVIRONMENT: "Development"
        Host: "host.docker.internal"
        Port: "1401"
        Database: "AccountsDB"
        UserId: "sa"
        Password: "Sql1234!"
        RemoteClientServiceHTTPSPort: "7149"
        isDevelopment: "true"
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/